spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user-service
    username: postgres
    password: postgres123
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 8081